app = "your-ghost-app-name"
primary_region = "sjc"

[build]

[http_service]
  internal_port = 2368
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  NODE_ENV = "production"
  url = "https://your-ghost-app-name.fly.dev"
  database__client = "sqlite3"
  database__connection__filename = "/var/lib/ghost/content/data/ghost.db"
  privacy__useUpdateCheck = "false"

[mounts]
  source = "ghost_data"
  destination = "/var/lib/ghost/content"
